-- ============================================================
-- SEED 02: Terms of Service
-- Source: file6 — BẢN QUYỀN TRÍ TUỆ GAME
-- ============================================================
INSERT INTO tos_documents (doc_key, content, version)
VALUES (
  'main_tos',
  E'BẢN QUYỀN TRÍ TUỆ GAME\n\n1. Tuyên bố quyền sở hữu\nToàn bộ nội dung của trò chơi này, bao gồm nhưng không giới hạn ở tên gọi, cốt truyện, bối cảnh, nhân vật, hình ảnh, biểu tượng, giao diện, âm thanh, nhạc nền, mã nguồn, dữ liệu hệ thống, thiết kế mỹ thuật, cơ chế vận hành, hệ thống kỹ năng, nhiệm vụ và các tài sản số liên quan, đều thuộc quyền sở hữu trí tuệ của tác giả hoặc đơn vị phát hành hợp pháp.\n\n2. Quy định bảo hộ\nMọi cá nhân hoặc tổ chức khi tiếp cận, sử dụng hoặc khai thác sản phẩm này đều phải tuân thủ nghiêm ngặt các quy định sau:\n\n— Không sao chép:\nNghiêm cấm sao chép toàn bộ hoặc một phần nội dung game dưới bất kỳ hình thức nào khi chưa có sự đồng ý bằng văn bản của chủ sở hữu. Bao gồm nhưng không giới hạn ở việc trích xuất dữ liệu, sao lưu trái phép, đăng tải lại hình ảnh, âm thanh, nội dung cốt truyện, nhân vật hoặc sử dụng các thành phần của game để tạo sản phẩm khác.\n\n— Không sửa đổi:\nNghiêm cấm mọi hành vi tự ý chỉnh sửa, cắt ghép, cải biên, dịch lại, thay đổi cơ chế, giao diện, hình ảnh, âm thanh, dữ liệu hoặc mã nguồn của game nếu chưa được cấp quyền hợp lệ từ chủ sở hữu.\n\n— Không xoá bỏ:\nNghiêm cấm xóa, che giấu, thay đổi hoặc làm sai lệch các thông tin nhận diện bản quyền như tên tác giả, tên nhà phát triển, logo, watermark, thông báo pháp lý hoặc bất kỳ dấu hiệu xác lập quyền sở hữu nào gắn liền với sản phẩm.\n\n3. Phạm vi áp dụng\nNhững quy định này áp dụng đối với mọi hình thức sử dụng, lưu trữ, chia sẻ, phát hành, khai thác thương mại hoặc phi thương mại có liên quan đến trò chơi và các tài sản cấu thành trò chơi.\n\n4. Trách nhiệm pháp lý\nMọi hành vi vi phạm quyền sở hữu trí tuệ đối với trò chơi đều có thể bị yêu cầu chấm dứt ngay lập tức, gỡ bỏ nội dung vi phạm, bồi thường thiệt hại và xử lý theo quy định của pháp luật hiện hành.\n\n5. Cam kết bảo vệ\nChủ sở hữu có toàn quyền theo dõi, ghi nhận và thực hiện các biện pháp cần thiết để bảo vệ tài sản trí tuệ của mình trước các hành vi sao chép, sửa đổi hoặc xóa bỏ trái phép.\n\n6. Kết luận\nBản quyền là nền tảng bảo vệ công sức sáng tạo. Vì vậy, mọi cá nhân và tổ chức đều phải tuyệt đối tôn trọng nguyên tắc:\nKHÔNG SAO CHÉP – KHÔNG SỬA ĐỔI – KHÔNG XOÁ BỎ\nđối với bất kỳ nội dung nào thuộc quyền sở hữu trí tuệ của game khi chưa được cho phép.',
  '1.0'
) ON CONFLICT (doc_key) DO UPDATE SET content = EXCLUDED.content, version = EXCLUDED.version;
